In [35]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [36]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Culleredo,ES,2020-11-07 19:33:33,43.29,-8.39,59.00,87,20,5.82
1,1,Oranjemund,NaN,2020-11-07 19:33:33,-28.55,16.43,63.28,85,33,3.13
2,2,Ponta Do Sol,PT,2020-11-07 19:33:33,32.67,-17.10,66.20,72,20,3.36
3,3,Pacocha,PE,2020-11-07 19:33:34,-17.58,-71.33,68.00,72,90,5.82
4,4,Lebu,CL,2020-11-07 19:33:17,-37.62,-73.65,56.68,61,0,22.19

In [37]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [38]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [39]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [41]:
# Heatmap of percent cloudines
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [48]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [49]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
13,13,Arraial Do Cabo,BR,2020-11-07 19:33:30,-22.97,-42.03,75.20,69,75,9.17
19,19,Salinopolis,BR,2020-11-07 19:33:42,-0.61,-47.36,83.97,72,22,16.58
26,26,Mmathubudukwane,BW,2020-11-07 19:33:45,-24.60,26.43,80.60,42,0,1.12
30,30,Mattru,SL,2020-11-07 19:33:46,7.62,-11.83,76.33,95,68,3.78
33,33,West Bay,KY,2020-11-07 19:29:24,19.37,-81.42,80.01,86,100,5.99
34,34,Bull Savanna,JM,2020-11-07 19:28:35,17.89,-77.59,76.37,89,100,14.25
39,39,Matara,LK,2020-11-07 19:29:14,5.95,80.54,77.88,86,0,5.61
41,41,El Tocuyo,VE,2020-11-07 19:33:26,9.79,-69.79,75.20,78,87,11.41
46,46,Georgetown,MY,2020-11-07 19:31:39,5.41,100.34,78.80,88,40,3.36
53,53,Manassas Park,US,2020-11-07 19:33:58,38.78,-77.47,75.20,36,1,2.13

In [50]:
preferred_cities_df.count()

City_ID       190
City          190
Country       188
Date          190
Lat           190
Lng           190
Max Temp      190
Humidity      190
Cloudiness    190
Wind Speed    190
dtype: int64

In [51]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp    Lat     Lng Hotel Name
13  Arraial Do Cabo      BR     75.20 -22.97  -42.03
19      Salinopolis      BR     83.97  -0.61  -47.36
26  Mmathubudukwane      BW     80.60 -24.60   26.43
30           Mattru      SL     76.33   7.62  -11.83
33         West Bay      KY     80.01  19.37  -81.42
34     Bull Savanna      JM     76.37  17.89  -77.59
39           Matara      LK     77.88   5.95   80.54
41        El Tocuyo      VE     75.20   9.79  -69.79
46       Georgetown      MY     78.80   5.41  100.34
53    Manassas Park      US     75.20  38.78  -77.47

In [52]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [53]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
13,Arraial Do Cabo,BR,75.20,-22.97,-42.03,Pousada Porto Praia
19,Salinopolis,BR,83.97,-0.61,-47.36,Salinas Park Resort Maçarico AP101
26,Mmathubudukwane,BW,80.60,-24.60,26.43,Gill Sleepover Guesthouse
30,Mattru,SL,76.33,7.62,-11.83,Boima Gbondo's Compound
33,West Bay,KY,80.01,19.37,-81.42,Calypso Cove
34,Bull Savanna,JM,76.37,17.89,-77.59,Big Red's
39,Matara,LK,77.88,5.95,80.54,Amaloh Boutique Resort
41,El Tocuyo,VE,75.20,9.79,-69.79,HOTEL BOUTIQUE SANTO DOMINGO
46,Georgetown,MY,78.80,5.41,100.34,Cititel Penang
53,Manassas Park,US,75.20,38.78,-77.47,Holiday Inn Manassas - Battlefield

In [55]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [58]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [59]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))